### ISSUE TITLE
can't find ’mango‘which include ’Tuner‘ and 'Scheduler'

### ISSUE THREAD

**Issue by FIRELES** [deepfindr/gnn-project#15]
the pypi also cant find it ,did i miss the file? or the author already delete it ? I am confused

**Comment by Bernadette-Mohr** [comment]
It's potentially this: https://github.com/ARM-software/mango
Haven't tried running the code yet, so no guarantees.

**Comment by deepfindr** [comment]
Hi, yes mango from ARM is the right library.

Use pip install arm-mango to install it.
