### ISSUE TITLE
dataset_featurizer.py

### ISSUE THREAD

**Issue by mfaizan-ai** [deepfindr/gnn-project#6]

**Comment by mfaizan-ai** [comment]
I don't understand the logic you used to load data, there is no such file defined as self.raw_paths in your class. Furthermore, how would code understand the directory such self.processed_dir, it has not specified as well?

**Comment by deepfindr** [comment]
Hi!
Please take a look at the PyG documentation: https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html

This is the standard way to initialize a dataset.
All of the logic is handled by the parent dataset class (from which we inherit here).

Hope this helps :)

**Comment by mfaizan-ai** [comment]
ok got it. What is self.raw_paths? :)

**Comment by mfaizan-ai** [comment]
it should not self.filename?

**Comment by mfaizan-ai** [comment]
The script gives me the follownig error
FileNotFoundError: [Errno 2] No such file or directory: 'data\\raw\\HIV_test.csv'
while I passed following args to class 
test_dataset = MoleculeDataset(root="data/", filename="HIV_test.csv", test=True)

**Comment by mfaizan-ai** [comment]
I downloaded the csv files from your GitHub repo, and placed them under data directory

**Comment by mfaizan-ai** [comment]
I also passed full path to CSV file, but still it was giving me error

**Comment by deepfindr** [comment]
Hi! The dataset should be placed in "raw". As the documentation says: "We split up the root folder into two folders: the raw_dir, where the dataset gets downloaded to, and the processed_dir, where the processed dataset is being saved.". 

Therefore put the data into data/raw.

Hope this helps :)
