### ISSUE TITLE
Following videos

### ISSUE THREAD

**Issue by ethancohen123** [deepfindr/gnn-project#7]
Hi,
First thank you for all this amazing materials !
For my part, I have a lot of difficulties trying to follow the video and the code that seems to be the final project. 
Is there a way to get the scripts for each videos please ?
Thank you !

**Comment by deepfindr** [comment]
Hi! 

Unfortunately, I don't have separate parts, but two comments:

1. There are 2 dataset files - the video only talks about one of them
2. There is another branch with experiments

Which part of the code is difficult to follow along?

Best regards!
