### ISSUE TITLE
question on TransformerConv

### ISSUE THREAD

**Issue by RealNicolasBourbaki** [deepfindr/gnn-project#8]
Hi Deepfindr,

Thank you so much for you great video and code!

I have question on ```TransformerConv``` you used. You defined the layer as:
```
self.conv1 = TransformerConv(feature_size, 
                                    embedding_size, 
                                    heads=n_heads, 
                                    dropout=dropout_rate,
                                    edge_dim=edge_dim,
                                    beta=True) 
```
but according to ```PyG``` website, you are supposed to have ```in_channel``` as the first parameter, which is either a tuple defining the shape of the input, or -1, which derive the size from the first input(s) to the forward method.

but ```feature_size``` is either of them. Is it a version issue? which version of PyG did you use for the tutorial?

Thank you so much!

Best,
Nicole

**Comment by RealNicolasBourbaki** [comment]
Nevermind, misread the documentation. Solved!

**Comment by deepfindr** [comment]
Ok great :)
