### ISSUE TITLE
Where does the 0 come from ?

### ISSUE THREAD

**Issue by SuroshAhmadZobair** [deepfindr/gnn-project#9]
Hi
Thank you for all your effort on the Gnn-project. 

Once the training is done:
 ```
Processing...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3999/3999 [00:27<00:00, 145.31it/s]
Done!
Loading model...
...
...
...
    if i % self.top_k_every_n == 0:
ZeroDivisionError: integer division or modulo by zero
```
 Any insights @deepfindr 

Thanks in advance

**Comment by deepfindr** [comment]
Hi!
Did you set top_k_every_n to 0?
That is invalid because it leads to division by zero.
:)

**Comment by SuroshAhmadZobair** [comment]
Thanks for your quick response.

By default it was 0 in the config file. I should have searched myself. I changed it to 1 and it works fine now.

Thanks
